{
  "formatVersion": "1.1",
  "component": {
    "group": "titanium",
    "module": "titanium.nisshi3",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "titanium.nisshi3-5.0.0.jar",
          "url": "titanium.nisshi3-5.0.0.jar",
          "size": 54392,
          "sha512": "a5ec09e77fb35ce252adc0eea6e7c009991addffd253351b663cbe5dee6f997a11acab11adfe8b210287cf321a3599daf1b8c2dce45e299510588c947fd79e48",
          "sha256": "3a9d043274b2606a2ea16f87f0212873b03fbc86b2ab92c041388279322daa22",
          "sha1": "b5b6fa33d65d914d776823da8e8cc599f3796c9d",
          "md5": "2f7e58744895f8165b5a7202fa6d7ddc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "titanium.nisshi3-5.0.0.jar",
          "url": "titanium.nisshi3-5.0.0.jar",
          "size": 54392,
          "sha512": "a5ec09e77fb35ce252adc0eea6e7c009991addffd253351b663cbe5dee6f997a11acab11adfe8b210287cf321a3599daf1b8c2dce45e299510588c947fd79e48",
          "sha256": "3a9d043274b2606a2ea16f87f0212873b03fbc86b2ab92c041388279322daa22",
          "sha1": "b5b6fa33d65d914d776823da8e8cc599f3796c9d",
          "md5": "2f7e58744895f8165b5a7202fa6d7ddc"
        }
      ]
    }
  ]
}
